#!/usr/bin/env python3
"""Derive answers from cross-country statistical indicators.

Writes src/data/indicator-answers.json in the same schema as the hand-written
sourced-answers.json, so both feed the same loader.

Some Protocol questions are not really about a legal instrument. "Cost of
finance at rates to scale technology" asks a numeric question with a numeric
rubric, and a single comparable dataset answers it for every country at once —
far cheaper than researching 90 jurisdictions individually.

These answers carry basis "proxy-indicator" rather than "national", because a
general indicator is not the same thing as evidence about consumer energy
finance specifically. A country with a dedicated subsidised green-loan scheme
may do better for CERs than its commercial lending rate suggests, and a
hand-written national answer should override this one where it exists.
"""

import json
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src" / "data" / "indicator-answers.json"
INDEX = REPO / "src" / "data" / "jurisdictions.json"
CACHE = REPO / ".cache"

WB_API = (
    "https://api.worldbank.org/v2/country/all/indicator/{indicator}"
    "?format=json&per_page=20000&mrnev=1"
)

LENDING_RATE = "FR.INR.LEND"

# Row 12: "Cost of finance at rates to scale technology"
#   0 = at or above 10%   |   1 = above 5% and below 10%   |   2 = at or below 5%
def lending_rate_score(rate: float) -> int:
    if rate <= 5:
        return 2
    if rate < 10:
        return 1
    return 0


def fetch(indicator: str) -> list[dict]:
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"wb_{indicator}.json"
    if not path.exists():
        url = WB_API.format(indicator=indicator)
        print(f"downloading {url}")
        urllib.request.urlretrieve(url, path)
    payload = json.loads(path.read_text())
    return [row for row in payload[1] if row.get("value") is not None]


def main() -> None:
    known = {j["code"] for j in json.loads(INDEX.read_text())}
    rows = fetch(LENDING_RATE)

    answers = []
    skipped = []
    for row in rows:
        # The World Bank's country.id is a two-letter code, but the list also
        # contains aggregates (regions, income groups) that are not places.
        code = row["country"]["id"]
        if code not in known:
            skipped.append(code)
            continue

        rate = row["value"]
        year = row["date"]
        answers.append(
            {
                "countries": [code],
                "row": 12,
                "score": lending_rate_score(rate),
                "basis": "proxy-indicator",
                "sourceId": "wb-lending-rate",
                "note": (
                    f"Commercial bank lending rate was {rate:.1f}% in {year} "
                    f"(World Bank, indicator {LENDING_RATE}). "
                    "This is the general rate charged to the private sector, used here as a "
                    "proxy for what a household or business would pay to finance CERs. A "
                    "dedicated subsidised green-loan scheme could make CER finance cheaper "
                    "than this figure implies, so a researched national answer should "
                    "replace it where one exists."
                ),
            }
        )

    out = {
        "README": (
            "Generated by scripts/build_indicator_answers.py — do not edit by hand. "
            "Answers derived from cross-country statistical indicators, carrying basis "
            "'proxy-indicator'. Hand-written answers in sourced-answers.json take "
            "precedence at equal specificity."
        ),
        "sources": {
            "wb-lending-rate": {
                "title": (
                    "World Bank — Lending interest rate (%), indicator FR.INR.LEND, "
                    "most recent year available per country"
                ),
                "url": "https://data.worldbank.org/indicator/FR.INR.LEND",
            }
        },
        "groups": {},
        "answers": answers,
    }

    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")

    dist = {0: 0, 1: 0, 2: 0}
    for a in answers:
        dist[a["score"]] += 1
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  {len(answers)} countries scored on row 12")
    print(f"  score 2 (<=5%): {dist[2]}   score 1 (5-10%): {dist[1]}   score 0 (>=10%): {dist[0]}")
    print(f"  {len(skipped)} entries skipped as aggregates or unknown codes")


if __name__ == "__main__":
    main()
